// Generated by CoffeeScript 1.10.0
(function() {
  var browserify, gulp, sass, source;

  gulp = require('gulp');

  source = require('vinyl-source-stream');

  browserify = require('browserify');

  sass = require('gulp-sass');

  gulp.task('sass', function() {
    return gulp.src('sass/**/*sass').pipe(sass()).pipe(gulp.dest('./css'));
  });

  gulp.task('build', function() {
    return browserify({
      entries: ['./src/main.coffee'],
      extensions: ['.coffee', '.js']
    }).transform('coffeeify').bundle().pipe(source('main.js')).pipe(gulp.dest('build'));
  });

  gulp.task('default', ['build']);

}).call(this);
