// Generated by CoffeeScript 1.10.0
(function() {
  var gulp, sass;

  gulp = require("gulp");

  sass = require("gulp-sass");

  gulp.task('sass', function() {
    return gulp.src('sass/**/*sass').pipe(sass()).pipe(gulp.dest('./css'));
  });

}).call(this);
